### ISSUE TITLE
Insanely high upload time?

### ISSUE THREAD

**Issue by nprodas** [CalebEverett/arloader#15] opened 2022-03-02 22:28 UTC
Hey team!

Was not sure where the best place to put this was, but figured it couldn't hurt to have it here in case any other users experience this. 

My scenario:
Our project already minted and we want to add an extra attributes field in the metadata to specify the rarity of that NFT. This needs to be done for all 750 NFT's and we can easily update the URI that points to the metadata with something like [metaboss](https://github.com/samuelvanderwaal/metaboss). The problem we face is figuring out the best way to upload the updated JSONS into arweave. 

The issue:
I did some testing with only 1 JSON file following the available documentation. I used SOL and also specified the maximum amount for reward multiplier. Even with the increased rewards, the upload for a single JSON file took roughly 40 minutes before it showed up. 

Is there something I am doing wrong for it to take so long? 
Is there a better way to achieve what we are trying to do?

Any help would be greatly appreciated!

**Comment by CalebEverett** [comment] 2022-03-03 05:38
Feel free to dm me on discord if you want some real time help: @Caleb#9071.

That sounds like a long time, but if it ultimately showed up, it could be a gateway issue. Depending on the size of your files, there are a several different things we could try to get things up there faster.

For starters, make sure you are on the latest version: 0.1.59. That should have a max reward multiplier of 3 and with just 760 json files should just be a single bundle.

**Comment by nprodas** [comment] 2022-03-08 23:16
Hey, I sent you a friend request on discord, my user name is @NoRelax#5788

**Comment by CalebEverett** [comment] 2022-03-09 00:03
Hi @nprodas I didn't see that in discord, but happy to help. Are you still experiencing delays? I think the arweave gateway was behind today.

**Comment by paul-hl** [comment] 2022-03-09 10:20
I also sent you a friend request. If I may, I would like to discuss upload times as well. It seems slow.. thank you

**Comment by CalebEverett** [comment] 2022-03-09 14:14
Hi @paul-hl I didn't get that one either, but what seems to be the trouble? Are you having issues with the time it takes to complete the initial upload of files or time it takes before they are confirmed and/or available?

**Comment by CalebEverett** [comment] 2022-03-09 16:52
I think the markdown was getting my discord address with a lower case c instead of upper case.

`@Caleb#9071`

**Comment by CalebEverett** [comment] 2022-03-10 16:51
One other suggestion generally is that sometimes it seems the indexing of the bundles can take some time on the network, so if you have only a small number of files to upload, <100 or so, you can pass the `--no-bundle` flag and they will be uploaded as individual transactions, not bundled together. They will then be available without the network having to index any bundles.

**Comment by paul-hl** [comment] 2022-03-10 20:38
Thanks for the suggestion. I had arrived to this solution myself as well but I am glad to know why it is quicker (and better in my case).

And I meant that it is so slow not to upload the image itself, but it takes a lot of time before it is actually viewable when using upload-nft. 

I just need to upload single images, so no-bundle is a great option for me.

However, I am getting Submitted and after a few seconds NotFound status of my transaction today. I have two questions about that. I am using --reward-multiplier 3.0. It came through to Confirmed just once this afternoon. 

My questions:
1. I can see that the SOL was transferred. So it means, when the transaction is rejected by Arweave, they still keep the fee? :-D
2. Is it often that the tx is rejected (NotFound)?
3. I can see the image even if the tx is NotFound but I am not sure it will stay available after some time.

Thanks.

**Comment by CalebEverett** [comment] 2022-03-10 21:33
@paul-hl  I think the gateway has been having issues with the bundles the last couple of days. I am checking to make sure it is not an arloader issue, but I have been hearing of other people experiencing delays as well. Try starting with 2 on the reward multiplier, sometimes they can get rejected for too much reward. If the SOL was transferred and your arweave tx failed, send me a list of tx and I can send it back to you - sorry it is manual right now. And that is right, you can't rely on being able to see the image as confirmation it has been permanently added - you have to relay on number of confirmations and being able to retrieve the data from https://aweave.net/tx/ or https://aweave.net/chunk/.

**Comment by paul-hl** [comment] 2022-03-10 21:54
@CalebEverett thanks. 

I tried reward 2, 2.5, still getting NotFound multiple times or sometimes I get SolanaNetworkError.

Do you think using AR token for payment, or alternatively the arbk tool from arweave, is more reliable? I prefer paying in SOL, but..

**Comment by CalebEverett** [comment] 2022-03-10 22:35
I can try here to see if I am having the same issues.

**Comment by CalebEverett** [comment] 2022-03-11 00:28
@paul-hl I was able to upload single transactions ok here with AR. I was having trouble with SOL, which means that the SOL network is taking longer than 10 seconds to finalize transactions. When that happens, you can wait until later or try using AR.

**Comment by paul-hl** [comment] 2022-03-11 00:31
@CalebEverett thank you for trying this out.

**Comment by CalebEverett** [comment] 2022-03-11 00:54
@paul-hl no worries - let me know if you need a little AR to tide you over - getting it can be a pain.

It can be tough to figure out exactly why transactions aren't going through as fast as they should or at all, unfortunately, given all the moving pieces, especially with paying with SOL. You've got arloader, solana and arweave (which depends on both the gateway for uploading and indexing and the nodes for actually writing to the chain), all in the mix and they all have to be working in order for things to go smoothly.  This or dm on discord is the right place for arloader.

For arweave, you can run `arloader pending` to check the pending transaction volume - if that is over 1,000 then it could be a congestion issue. There are also potential gateway issues, but I don't think there is a gateway status site, so you have to check the arweave discord. You can also try https://scar.vercel.app/ or https://viewblock.io/arweave. If you see big lags in the time since the last transaction was created or you see bundle transactions that are not being indexed to show the included data items older than an hour or so, that usually means something is up.

For solana you can check https://explorer.solana.com/ or https://status.solana.com/. In particular, look at the Ping tx_loss (Mainnet-Beta), which should be close to zero. Been over 50% for the last hour and up and down all day.

**Closed** 2022-03-31 04:37 UTC
